import { Taak } from './taak';
import DateTimeFormat = Intl.DateTimeFormat;

export const TAKEN: Taak[] = [
  {
    name: 'Konijntjes',
    timeLimit: 3,
    deadline: null,
    deadline_time: null,
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 4.5,
    description: 'Konijnenhok opruimen',
    finished: false,
  },
  {
    name: 'Groenteafval',
    timeLimit: 14,
    deadline: null,
    deadline_time: ['Sunday', 22],
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 4,
    description: 'Elke zondag avond kan het groente afval naar de straat gebracht worden.',
    finished: false,
  },
  {
    name: 'Restafval',
    timeLimit: 7,
    deadline: null,
    deadline_time: ['Thursday', 22],
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 4,
    description: 'Elke woensdag avond tot donderdagochtend voor 10:00 kan het restafval weggebracht worden',
    finished: false,
  },
  {
    name: 'Plastic/Glas/Papier',
    timeLimit: 14,
    deadline: null,
    deadline_time: null,
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 8.5,
    description: 'Breng het plastic glas en papier weg',
    finished: false,
  },
  {
    name: 'Keuken',
    timeLimit: 14,
    deadline: null,
    deadline_time: null,
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 6.5,
    description: 'Fornuis, oven, aanrecht, afdruiprek',
    finished: false,
  },
  {
    name: 'Stofzuigen beneden',
    timeLimit: 14,
    deadline: null,
    deadline_time: null,
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 4.5,
    description: 'Lekker zuigen',
    finished: false,
  },
  {
    name: 'Stofzuigen trap/boven',
    timeLimit: 14,
    deadline: null,
    deadline_time: null,
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 5,
    description: 'Stofzuigen maar dan high',
    finished: false,
  },
  {
    name: 'Dweilen',
    timeLimit: 28,
    deadline: null,
    deadline_time: null,
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 4,
    description: 'Mop that kitchen flo, clean that hallway yo',
    finished: false,
  },
  {
    name: 'Water closet',
    timeLimit: 14,
    deadline: null,
    deadline_time: null,
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 6,
    description: 'Use that chloride, show your shiny side',
    finished: false,
  },
  {
    name: 'Kledingwas',
    timeLimit: 7,
    deadline: null,
    deadline_time: null,
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 5.5,
    description: 'Don\'t fuck it up!',
    finished: false,
  },
  {
    name: '60gradenwas',
    timeLimit: 7,
    deadline: null,
    deadline_time: null,
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 4.5,
    description: 'Clean blankets and towlies please',
    finished: false,
  },
  {
    name: 'Beddengoed verschonen',
    timeLimit: 14,
    deadline: null,
    deadline_time: null,
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 6.5,
    description: 'Oh my! Lordy lord',
    finished: false,
  },
  {
    name: 'Marel\'s tiny little corner considering the whole universe',
    timeLimit: 7,
    deadline: null,
    deadline_time: null,
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 4.5,
    description: 'Maak dat gootsteentje schoon',
    finished: false,
  },
  {
    name: 'De uithoeken van slaapland',
    timeLimit: 28,
    deadline: null,
    deadline_time: null,
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 7,
    description: 'Onder het bed achter het bed naast het bed doe een gebed',
    finished: false,
  },
  {
    name: 'Oppervlaktes stoffen',
    timeLimit: 14,
    deadline: null,
    deadline_time: null,
    timeLeft: 0,
    daysLeft: 0,
    hoursLeft: 0,
    minutesLeft: 0,
    effort: 6.5,
    description: 'Oh my! Lordy lord',
    finished: false,
  },

];

